import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getAlternatives, getProduct, getProducts } from "@/lib/catalog";
import { ProductCard } from "@/components/product-card";
import { SponsorSlot } from "@/components/sponsor-slot";
import { absolute } from "@/lib/site";
export async function generateStaticParams(){return (await getProducts()).map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const p=await getProduct(slug);return p?{title:`Alternatives to ${p.name}`,description:`Curated alternatives to ${p.name} with feature and use-case context.`,alternates:{canonical:absolute(`/alternatives/${p.slug}`)},openGraph:{title:`Alternatives to ${p.name}`,description:`Curated alternatives to ${p.name} with feature and use-case context.`,url:absolute(`/alternatives/${p.slug}`)}}:{};}
export default async function Alternatives({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const p=await getProduct(slug);if(!p)notFound();const alts=await getAlternatives(p);const jsonLd={"@context":"https://schema.org","@type":"CollectionPage",name:`Alternatives to ${p.name}`,description:`Curated alternatives to ${p.name} with feature and use-case context.`,url:absolute(`/alternatives/${p.slug}`),mainEntity:{"@type":"ItemList",itemListElement:alts.map((a,index)=>({"@type":"ListItem",position:index+1,name:a.name,url:absolute(`/products/${a.slug}`)}))}};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><section className="section"><div className="container"><span className="eyebrow">Alternatives</span><h1>Alternatives to {p.name}</h1><p className="section-intro">If {p.name} does not fit, these curated options cover adjacent needs in {p.category.toLowerCase()}.</p><SponsorSlot/><div className="grid">{alts.map(a=><ProductCard key={a.slug} product={a}/>)}</div><div className="panel section"><h2>How to choose</h2><p className="muted">Compare workflow, pricing model, integrations, migration requirements, team size and the exact use case behind the purchase.</p><Link className="btn secondary" href={`/products/${p.slug}`}>Return to {p.name}</Link></div></div></section></>;}